### ISSUE TITLE
Mudar Página Principal

### ISSUE THREAD

**Issue by Inftek** [marciomrs4/invtek#3]
Mudar titulo Ceadis e a descrição.

Mudar a cor do fundo para este:
.bg-aqua-active, .modal-info .modal-header, .modal-info .modal-footer {
    background-color: #ccc !important;
}

CEADIS
Centro Estadual de Armazenamento e Distribuição de Insumos de Saúde do Estado de São Paulo

Colocar no lugar: 
INFTEK
Soluções de sistemas

2016
TECNOLOGIA CEADIS

Colocar no lugar:

2016
TECNOLOGIA INFTEK

Trocar o Favicon do Symfony para o Inftek : http://infotektecnologia.com.br/favicon.ico

**Comment by marciomrs4** [comment]
That funcionality is now in configuration, (parameters.yml)
